'use strict';
const E=MathEngine,$=id=>document.getElementById(id),fmt=v=>Number.isFinite(v)?Number(v.toPrecision(9)).toString():'—';
let model=null,scope={},configs={},result=null,domain=null,view=null,frame=0,boundaryTimer=0;
const presets={A:['(x-a)^2','0','4'],B:['x^2','a','a+2'],C:['-(x-a)^2+4','0','4'],D:['(x-a)^2','a-1','3']};
function el(tag,text,className){const n=document.createElement(tag);if(text!==undefined)n.textContent=text;if(className)n.className=className;return n;}
function apply(){try{const f=E.parse($('formula').value),l=E.parse($('left').value),r=E.parse($('right').value);if(E.variables(l).has('x')||E.variables(r).has('x'))throw Error('定義域の端点に x は使えません。');const names=[...new Set([...E.variables(f),...E.variables(l),...E.variables(r)])].filter(n=>n!=='x').sort();model={f,l,r,names};for(const n of names){if(!configs[n])configs[n]={min:-5,max:6,step:.05,initial:0};if(!(n in scope))scope[n]=0;}buildParameters();update(true);}catch(e){showError(e.message);}}
function buildParameters(){ $('parameters').replaceChildren();for(const n of model.names){const c=configs[n],box=el('div',undefined,'parameter'),row=el('div',undefined,'row'),label=el('label',n),number=el('input');number.type='number';number.step='any';number.value=scope[n];number.setAttribute('aria-label',n+' の値');row.append(label,number);const slider=el('input');slider.type='range';slider.min=c.min;slider.max=c.max;slider.step=c.step;slider.value=scope[n];slider.setAttribute('aria-label',n+' スライダー');const setValue=v=>{if(!Number.isFinite(v))return;scope[n]=v;number.value=v;slider.value=v;queueUpdate();};slider.addEventListener('input',()=>setValue(Number(slider.value)));number.addEventListener('input',()=>{if(number.value!=='')setValue(Number(number.value));});const details=el('details'),summary=el('summary','範囲と刻み幅'),settings=el('div',undefined,'settings');for(const [key,title] of [['min','最小'],['max','最大'],['step','刻み']]){const lab=el('label',title),input=el('input');input.type='number';input.step='any';input.value=c[key];lab.append(input);settings.append(lab);input.addEventListener('change',()=>{const v=Number(input.value),next={...c,[key]:v};if(!Number.isFinite(v)||next.min>=next.max||next.step<=0){input.value=c[key];return;}Object.assign(c,next);slider.min=c.min;slider.max=c.max;slider.step=c.step;update(false);});}details.append(summary,settings);box.append(row,slider,details);$('parameters').append(box);}if(!model.names.length)$('parameters').append(el('p','この式にはパラメータがありません。','hint'));const prior=$('boundaryParam').value;$('boundaryParam').replaceChildren(...model.names.map(n=>{const o=el('option',n);o.value=n;return o;}));if(model.names.includes(prior))$('boundaryParam').value=prior;$('boundaryLabel').hidden=!model.names.length;}
function queueUpdate(){if(!frame)frame=requestAnimationFrame(()=>{frame=0;update(false);});}
function showError(message){result=null;$('error').hidden=false;$('error').textContent=message;$('accuracy').textContent='判定できません';for(const id of ['minValue','maxValue'])$(id).textContent='—';for(const id of ['minAt','maxAt','explanation','boundaries'])$(id).replaceChildren();draw();}
function pretty(source){const frag=document.createDocumentFragment();let pieces=source.split(/(\^[+-]?\d+(?:\.\d+)?)/g);for(const part of pieces){if(part.startsWith('^'))frag.append(el('sup',part.slice(1)));else frag.append(document.createTextNode(part.replace(/\*/g,' · ').replace(/-/g,'−')));}return frag;}
function update(fit){try{domain=[E.evaluate(model.l,scope),E.evaluate(model.r,scope)];result=E.solve(model.f,scope,...domain);$('error').hidden=true;$('mathDisplay').replaceChildren(document.createTextNode('f(x) = '),pretty($('formula').value),el('br'),document.createTextNode(`${fmt(domain[0])} ≦ x ≦ ${fmt(domain[1])}`));$('accuracy').textContent=result.exact?'解析的判定 · 二次／一次／定数関数':'数値探索の近似候補 · 大域的な保証なし';for(const kind of ['min','max']){ $(kind+'Value').textContent=(result.exact?'':'≈ ')+fmt(result[kind]);$(kind+'At').textContent=result.constant?'定義域のすべての x で達成':`x ${result.exact?'=':'≈'} ${result[kind+'X'].slice(0,12).map(fmt).join(', ')}${result[kind+'X'].length>12?' …（ほかにも候補あり）':''}`;}explain();if(fit||!view)fitView();draw();clearTimeout(boundaryTimer);boundaryTimer=setTimeout(findBoundaries,100);}catch(e){showError(e.message);}}
function explain(){const box=$('explanation');box.replaceChildren();const [L,R]=domain;if(!result.exact){box.append(el('p','閉区間全体で連続となることを対応する式の範囲で確認し、2048分割と局所探索で候補を求めています。細かい振動や狭い山・谷を見落とす可能性があります。一般の関数の厳密な場合分けは生成しません。'));return;}const p=result.p,A=p[2]||0,B=p[1]||0;if(L===R){box.append(el('p','定義域は1点です。この点の値が最大値でも最小値でもあります。'));return;}if(A===0){box.append(el('p',B===0?'定数関数です。定義域全体で最大値と最小値が一致します。':B>0?'一次関数で増加します。左端で最小、右端で最大です。':'一次関数で減少します。左端で最大、右端で最小です。'));return;}const v=result.vertex,up=A>0,inner=up?'最小':'最大',outer=up?'最大':'最小',mid=L+(R-L)/2;box.append(el('p',`二次の係数 A = ${fmt(A)}。${up?'下に凸':'上に凸'}で、頂点の x 座標は v = −B/(2A) = ${fmt(v)}。`));box.append(el('p',`${inner}：${v<L?'頂点が左端より左にあるため、左端':v>R?'頂点が右端より右にあるため、右端':v===L?'頂点と左端が一致':v===R?'頂点と右端が一致':'頂点が定義域内にあるため、頂点'}で達成。`));const diff=A*(L-R)*(L+R-2*v);box.append(el('p',`${outer}：${v===mid?'左右の端点の値が等しいため、両端':(up?diff>0:diff<0)?'左端が頂点から遠いため、左端':'右端が頂点から遠いため、右端'}で達成。区間の中点は ${fmt(mid)} です。`));const table=el('table');for(const [condition,location] of [[`v < L`,`${inner}は左端`],[`L ≦ v ≦ R`,`${inner}は頂点`],[`R < v`,`${inner}は右端`],[`v < (L+R)/2`,`${outer}は右端`],[`v = (L+R)/2`,`${outer}は両端`],[`v > (L+R)/2`,`${outer}は左端`]]){const tr=el('tr');tr.append(el('td',condition),el('td',location));table.append(tr);}box.append(table,el('p','L は左端、R は右端。端点の比較は f(L) − f(R) = A(L−R)(L+R−2v) から説明できます。'));}
function findBoundaries(){const box=$('boundaries');box.replaceChildren();if(!model||!result)return;const n=$('boundaryParam').value;if(!n){box.append(el('p','パラメータがないため境界比較はありません。','hint'));return;}if(!result.exact){box.append(el('p','一般の関数の境界値は自動判定しません。','hint'));return;}const c=configs[n],width=c.max-c.min;
 const quantities=t=>{const s={...scope,[n]:t},p=E.polynomial(model.f,s),L=E.evaluate(model.l,s),R=E.evaluate(model.r,s);if(!p)return null;const A=p[2]||0,B=p[1]||0;return [B+2*A*L,B+2*A*R,B+A*(L+R),A,R-L];};
 const titles=['頂点と左端の一致','頂点と右端の一致','両端の値の一致','二次の係数が0','定義域が1点'];let roots=[];
 const analytic=E.boundaryEquations(model.f,model.l,model.r,scope,n);
 // These are numerical roots of the derived equations, not symbolic parameter inequalities.
 for(let k=0;k<5;k++){if(analytic?.[k]){for(const t of analytic[k].roots)if(Number.isFinite(t)&&t>=c.min&&t<=c.max)roots.push({t,k,analytic:true});continue;}let lastT=c.min,last=quantities(lastT)?.[k];let values=Array.from({length:65},(_,i)=>quantities(c.min+width*i/64)?.[k]);if(values.every(v=>v===0))continue;for(let i=1;i<=512;i++){let t=c.min+width*i/512,v=quantities(t)?.[k];if(Number.isFinite(last)&&Number.isFinite(v)){if(last===0)roots.push({t:lastT,k});if(last*v<0){let lo=lastT,hi=t,z=last;for(let j=0;j<45;j++){let mid=(lo+hi)/2,w=quantities(mid)?.[k];if(!Number.isFinite(w))break;if(z*w<=0)hi=mid;else{lo=mid;z=w;}}roots.push({t:(lo+hi)/2,k});}if(i===512&&v===0)roots.push({t,k});}lastT=t;last=v;}}
 roots.sort((a,b)=>a.t-b.t);roots=roots.filter((r,i,arr)=>!arr.slice(0,i).some(q=>q.k===r.k&&Math.abs(q.t-r.t)<width*1e-7));
 if(!roots.length){box.append(el('p','設定した範囲では境界候補を検出していません。接するだけの根など、探索で見落とす場合があります。','hint'));return;}
 for(const root of roots.slice(0,20)){const s={...scope,[n]:root.t},p=E.polynomial(model.f,s),L=E.evaluate(model.l,s),R=E.evaluate(model.r,s);if(root.k<3&&(!p||!p[2]||L>R))continue;const card=el('div',undefined,'boundary'+(Math.abs(scope[n]-root.t)<1e-7*Math.max(1,Math.abs(root.t))?' active':''));card.append(el('strong',`${n} ${root.analytic?'=':'≈'} ${fmt(root.t)}`),el('small',titles[root.k]+(root.analytic?' · 方程式から解析（表示は丸め）':' · 数値的な境界候補')));const row=el('div',undefined,'row');const eps=Math.max(width/1000,Math.min(c.step,width/100));for(const [label,offset] of [['直前',-eps],['境界',0],['直後',eps]]){const b=el('button',label);b.title=`${n} = ${fmt(root.t+offset)}`;b.onclick=()=>{scope[n]=root.t+offset;buildParameters();update(false);};row.append(b);}card.append(row);box.append(card);}box.append(el('p','頂点と端点・中点の一致、係数0、区間の退化が境界です。パラメータについて二次以下の方程式は解析し、それ以外は数値探索します。数値探索では境界を見落とすことがあります。','hint'));}
function fitView(){if(!domain)return;const [L,R]=domain,span=Math.max(2,R-L),xmin=L-span*.3,xmax=R+span*.3;let ys=[0];for(let i=0;i<=100;i++){const y=E.evaluate(model.f,{...scope,x:L+(R-L)*i/100});if(Number.isFinite(y))ys.push(y);}if(result)ys.push(result.min,result.max);let low=Math.min(...ys),high=Math.max(...ys),height=Math.max(2,high-low);view={xmin,xmax,ymin:low-height*.2,ymax:high+height*.25};}
function draw(){const canvas=$('graph'),rect=canvas.getBoundingClientRect(),dpr=window.devicePixelRatio||1;canvas.width=Math.round(rect.width*dpr);canvas.height=Math.round(rect.height*dpr);const ctx=canvas.getContext('2d');ctx.scale(dpr,dpr);const W=rect.width,H=rect.height;if(!model||!view)return;const {xmin,xmax,ymin,ymax}=view,X=x=>(x-xmin)/(xmax-xmin)*W,Y=y=>H-(y-ymin)/(ymax-ymin)*H;const step=span=>{let raw=span/8,p=10**Math.floor(Math.log10(raw));return (raw/p<2?1:raw/p<5?2:5)*p;};ctx.font='12px system-ui';ctx.lineWidth=1;
 for(const [lo,hi,s,vertical] of [[xmin,xmax,step(xmax-xmin),true],[ymin,ymax,step(ymax-ymin),false]]){for(let t=Math.ceil(lo/s)*s,j=0;t<=hi&&j<100;t+=s,j++){ctx.strokeStyle='#e4eaf2';ctx.beginPath();vertical?(ctx.moveTo(X(t),0),ctx.lineTo(X(t),H)):(ctx.moveTo(0,Y(t)),ctx.lineTo(W,Y(t)));ctx.stroke();ctx.fillStyle='#607088';ctx.fillText(fmt(Math.abs(t)<s*1e-8?0:t),vertical?X(t)+4:5,vertical?Math.min(H-5,Math.max(15,Y(0)+16)):Y(t)-4);}}
 ctx.strokeStyle='#6f8097';ctx.beginPath();ctx.moveTo(X(0),0);ctx.lineTo(X(0),H);ctx.moveTo(0,Y(0));ctx.lineTo(W,Y(0));ctx.stroke();ctx.fillText('x',W-14,Math.min(H-8,Math.max(16,Y(0)-8)));ctx.fillText('y',Math.min(W-16,Math.max(8,X(0)+8)),14);
 const curve=(lo,hi,color,width)=>{ctx.strokeStyle=color;ctx.lineWidth=width;ctx.beginPath();let started=false,prev=null;for(let i=0;i<=Math.ceil(W*2);i++){let x=lo+(hi-lo)*i/Math.ceil(W*2),y=E.evaluate(model.f,{...scope,x}),py=Y(y);if(!Number.isFinite(y)||Math.abs(py)>H*20||prev!==null&&Math.abs(py-prev)>H*2){started=false;prev=py;continue;}if(!started){ctx.moveTo(X(x),py);started=true;}else ctx.lineTo(X(x),py);prev=py;}ctx.stroke();};curve(xmin,xmax,'#bdc6d2',2);
 if(domain&&domain[0]<=domain[1]){ctx.fillStyle='rgba(34,107,214,.045)';ctx.fillRect(X(domain[0]),0,X(domain[1])-X(domain[0]),H);curve(Math.max(xmin,domain[0]),Math.min(xmax,domain[1]),'#226bd6',3);ctx.setLineDash([5,5]);ctx.strokeStyle='#226bd6';ctx.lineWidth=1;for(const x of domain){ctx.beginPath();ctx.moveTo(X(x),0);ctx.lineTo(X(x),H);ctx.stroke();}ctx.setLineDash([]);}
 const point=(x,y,color,r,label)=>{if(X(x)<-10||X(x)>W+10||Y(y)<-10||Y(y)>H+10)return;ctx.beginPath();ctx.arc(X(x),Y(y),r,0,Math.PI*2);ctx.fillStyle='white';ctx.fill();ctx.strokeStyle=color;ctx.lineWidth=3;ctx.stroke();if(label){ctx.fillStyle=color;ctx.fillText(label,Math.min(W-90,Math.max(5,X(x)+10)),Math.max(16,Y(y)-12));}};
 if(result){if(result.vertex!==null&&result.vertex!==undefined){const v=result.vertex;ctx.strokeStyle='#8855bb';ctx.lineWidth=1.5;ctx.setLineDash([6,5]);ctx.beginPath();ctx.moveTo(X(v),0);ctx.lineTo(X(v),H);ctx.stroke();ctx.setLineDash([]);point(v,E.evaluate(model.f,{...scope,x:v}),'#8855bb',9,'頂点');}for(const x of domain)point(x,E.evaluate(model.f,{...scope,x}),'#226bd6',4);for(const x of result.maxX.slice(0,50))point(x,result.max,'#cc3f47',8,'最大');for(const x of result.minX.slice(0,50))point(x,result.min,'#087e60',5,'最小');}}
function zoom(factor){if(!view)return;const cx=(view.xmin+view.xmax)/2,cy=(view.ymin+view.ymax)/2,dx=(view.xmax-view.xmin)*factor/2,dy=(view.ymax-view.ymin)*factor/2;view={xmin:cx-dx,xmax:cx+dx,ymin:cy-dy,ymax:cy+dy};draw();}
$('formulaForm').onsubmit=e=>{e.preventDefault();apply();};$('preset').onchange=()=>{const p=presets[$('preset').value];if(p){['formula','left','right'].forEach((id,i)=>$(id).value=p[i]);scope={};configs={};apply();}else $('formula').focus();};$('resetParams').onclick=()=>{for(const n of model.names)scope[n]=configs[n].initial;buildParameters();update(false);};$('boundaryParam').onchange=findBoundaries;$('zoomIn').onclick=()=>zoom(.8);$('zoomOut').onclick=()=>zoom(1.25);$('fit').onclick=()=>{fitView();draw();};
let drag=null;$('graph').addEventListener('pointerdown',e=>{if(!view)return;drag={x:e.clientX,y:e.clientY,view:{...view}};$('graph').setPointerCapture(e.pointerId);});$('graph').addEventListener('pointermove',e=>{if(!drag)return;const r=$('graph').getBoundingClientRect(),dx=(e.clientX-drag.x)/r.width*(drag.view.xmax-drag.view.xmin),dy=(e.clientY-drag.y)/r.height*(drag.view.ymax-drag.view.ymin);view={xmin:drag.view.xmin-dx,xmax:drag.view.xmax-dx,ymin:drag.view.ymin+dy,ymax:drag.view.ymax+dy};draw();});for(const event of ['pointerup','pointercancel'])$('graph').addEventListener(event,()=>drag=null);$('graph').addEventListener('wheel',e=>{e.preventDefault();zoom(e.deltaY>0?1.1:.9);},{passive:false});new ResizeObserver(draw).observe($('graphWrap'));apply();

